auth_ic_url = "https://ic0.app"
auth_sign_key = ""
cookie_domain = "https://yral.com"
app_domain = "https://yral.com"

cloudflare_account_identifier = ""
cloudflare_api_token = ""
cloudflare_namespace_identifier = ""

google_auth_landing_url = "https://auth.yral.com/google_oauth2_response"
google_client_id = ""
google_client_secret = ""
