[auth]
ic_url = "https://ic0.app"
sign_key = ""
cookie_domain = "hot-or-not-auth.fly.dev"
app_url = "https://hot-or-not-web-leptos-ssr.fly.dev"

[cloudflare]
account_identifier = ""
api_token = ""
namespace_identifier = ""

[[oauth]]
provider_name = "google"
auth_landing_url = "https://hot-or-not-auth.fly.dev/google_oauth2_response"
client_id = ""
client_secret = ""
