# auth_ic_url = "https://ic0.app"
auth_ic_url = "http://127.0.0.1:4943"
auth_sign_key = ""

# cloudflare_config
cloudflare_account_identifier = ""
cloudflare_namespace_identifier = ""
cloudflare_api_token = ""
