name: Deploy to Fly on push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Cache rust dependencies and build output
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6-dev
          sudo update-ca-certificates
      - name: Build
        env:
          LEPTOS_BIN_TARGET_TRIPLE: x86_64-unknown-linux-gnu
        run: cargo leptos build --release
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy a docker container to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.HOT_OR_NOT_AUTH_FLY_IO_GITHUB_ACTION }}
        run: flyctl deploy --remote-only
